### ISSUE TITLE
Use travis-ci and GitHub Releases to build and host the AppImage

### ISSUE THREAD

**Issue by probonopd** [ifireball/btsync-app#1]
Happy to see this project. Just an idea, why not use travis-ci and GitHub Releases to build and host the AppImage. See .travis.yml of AppImageKit itself to get some inspiration.

**Comment by ifireball** [comment]
yeah, its on my roadmap :) 
thanks!

**Comment by ifireball** [comment]
Done :)

**Comment by probonopd** [comment]
Very cool!

**Comment by probonopd** [comment]
If you do not want to build AppImageKit each time you could also do something like

```
# Get and unpack AppImageAssistant
# sudo apt-get install -qq xorriso
wget "https://github.com/probonopd/AppImageKit/releases/download/1/AppImageAssistant"
xorriso -indev AppImageAssistant -osirrox on -extract / aia

# Generate AppImage from the AppDir
./aia/package ./Your.AppDir ./Your.AppImage
```

**Comment by ifireball** [comment]
I actually do want to build each time (E.g. basing my results on source as much as possible). But I'd like to be able to build only what's needed for the 'package' script without the rest of the AppImageAssistant GUI. It would also be nice if there was a stand-alone release of that, so it could be packaged as a build tool in distros.

**Comment by probonopd** [comment]
Thanks for the suggestion, I opened a ticket on https://github.com/probonopd/AppImageKit/issues/15

**Comment by probonopd** [comment]
Please see probonopd/AppImageKit#15
