### ISSUE TITLE
No module named requests

### ISSUE THREAD

**Issue by probonopd** [ifireball/btsync-app#3]
Launching the AppImage on Ubuntu 14.10 gives: `ImportError: No module named requests`. Bundling python-requests and python-urllib3 packages in the AppImage would probably solve this.

**Comment by ifireball** [comment]
I'm having a little trouble reproducing this, both libraries seem to be present on a default Ubuntu 14.10 desktop install (with unity).
@probonopd how did you arrive at your configuration?  I want to be able to make sure nothing else is missing.

**Comment by ifireball** [comment]
I figured it out - installing openssh-server pulls in those packages, so it was me making my default install dirty by enabling access to the machine...

**Comment by probonopd** [comment]
I like to use Live ISOs to test AppImages, this way you can be sure you pull in no external dependencies but the core OS.
